### ISSUE TITLE
'pip install trio-paho-mqtt' doesn't install trio_paho_mqtt

### ISSUE THREAD

**Issue by norwood867** [bkanuka/trio-paho-mqtt#1]
Running 'pip install trio-paho-mqtt' doesn't install trio_paho_mqtt directory or the trio_paho_mqtt.py file. 
This is with  python 3.7.5 on macos

**Comment by nm17** [comment]
Same here. It looks like the archive doesn't contain any python files. (Also it would be better if it was packaged using wheels)

**Comment by nm17** [comment]
![2019-12-28 11_22_02-C__Users_admin_Downloads_trio-paho-mqtt-0 3 0 tar gz_dist_trio-paho-mqtt-0 3 0 t](https://user-images.githubusercontent.com/23419131/71541066-56ec0c00-2964-11ea-81b7-85364c523d88.png)

**Comment by bkanuka** [comment]
Weird. This is a "works for me" issue, but I will definitely look into it in the next few days. Publishing on pypy is new to me.

**Comment by nm17** [comment]
I think I fixed it! #2 . Also next time use wheels instead of source archives.

**Comment by bkanuka** [comment]
Awesome! Thanks! I'm still on vacation but I'll test on my end and merge
when I get back

**Comment by norwood867** [comment]
Is there a way to grab the fix? thanks

**Comment by nm17** [comment]
@norwood867 Look at PR #2. It fixes the problem.

**Comment by norwood867** [comment]
what needs to happen so the fix will get picked up by pip so we can just deploy from there?
thanks

**Comment by bkanuka** [comment]
Sorry everyone. Family issues.  All fixed!  (?)  Should be able to pull from pip now
