### ISSUE TITLE
subscribe doesn't take the same parameters that paho takes

### ISSUE THREAD

**Issue by norwood867** [bkanuka/trio-paho-mqtt#3]
Here is an example:

    client.subscribe("temp/#", qos=0, client_id='furnace_receive')
TypeError: subscribe() got an unexpected keyword argument 'client_id'

**Comment by bkanuka** [comment]
Could you please share the whole stacktrace? I don't believe `subscribe` takes a `client_id` param: https://www.eclipse.org/paho/clients/python/docs/#subscribe-unsubscribe
